apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapp
  labels:
    app: fastapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapp
  template:
    metadata:
      labels:
        app: fastapp
    spec:
      containers:
        - name: fastapp
          image: newapp
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"