apiVersion: v1
kind: Service
metadata:
  name: fastapp
  labels:
    app: fastapp
spec:
  selector:
    app: fastapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 9000
      nodePort: 31100